### ISSUE TITLE
what is this ? 

### ISSUE THREAD

**Issue by sparrowmh** [darkoperator/MSF-Installer#38]
I've ruby 1.9.1 installed 
Errno::EACCES: Permission denied - metasploit-framework-4.11.0.pre.dev.gem
An error occurred while installing metasploit-framework (4.11.0.pre.dev), and
Bundler cannot continue.
Make sure that `gem install metasploit-framework -v '4.11.0.pre.dev'` succeeds
before bundling.
Ubuntu 12.04 precise

**Comment by sidjad** [comment]
Errno::EACCES: Permission denied - metasploit-framework-4.11.0.pre.dev.gem
An error occurred while installing metasploit-framework (4.11.0.pre.dev), and
Bundler cannot continue.
Make sure that `gem install metasploit-framework -v '4.11.0.pre.dev'` succeeds
before bundling.

i follow from " http://www.darkoperator.com/installing-metasploit-in-ubunt/ " this site

**Comment by darkoperator** [comment]
As the error clearly states it is a permission one. Use sudo for the bundle install

**Comment by sparrowmh** [comment]
i don't know why it's not working for some reason but if you use metasploit
without it will work perfectly i mean with payloads , msfvenom but they
wont work with SET... i combined two tutorials and then followed it and for
me it was working but not with SET.

**Comment by darkoperator** [comment]
did you modified the SET config file to point to the proper location?

**Comment by sparrowmh** [comment]
ohh of course i did i tried different and rights paths but :D as expected ,
nothing worked..

**Comment by darkoperator** [comment]
Sadly SET support is not part of the install script since it is mainly to setup a dev env quickly. if Metasploit working I will close the issue.

**Comment by sparrowmh** [comment]
ohh metasploit is working awesome on my vps and yes , you can close the
issue.

**Comment by sidjad** [comment]
Here is error I am facing during bundle install =
 Errno::EPERM: Operation not permitted - /opt/metasploit-framework/msfbinscan
An error occurred while installing metasploit-framework (4.11.0.pre.dev), and Bundler cannot
continue.
Make sure that `gem install metasploit-framework -v '4.11.0.pre.dev'` succeeds before
bundling.

**Comment by darkoperator** [comment]
Linux or OSX? RVM or not?

**Comment by sidjad** [comment]
ok i solve above problem but faceing new one related with armitage 
sudo sh -c "echo export MSF_DATABASE_CONFIG=/opt/metasploit-framework/config/database.yml >> /etc/profile
source /etc/profile"

give me error source not found  , instead of this in my ubuntu 14.04 LTS 64 bit have /etc/profile.d 
so how can i solve above problem

**Comment by darkoperator** [comment]
Remove the " at the end of the source command, do not copy paste the commands from the page do to formatting stuff being added, use tab complete

**Comment by sidjad** [comment]
![error](https://cloud.githubusercontent.com/assets/3491718/6130345/89ac8722-b16a-11e4-95f7-0770310ca081.png)
here all done ,please guide me where I made mistake ...

**Comment by sidjad** [comment]
![profile](https://cloud.githubusercontent.com/assets/3491718/6130680/b0e2a4be-b16c-11e4-9f58-0272a8d43957.png)
here is profile file

**Comment by darkoperator** [comment]
ou have 3 entries to create the env variable the last one possibly pointing to the wring location. remove the redundant ones and only leave the one that points to the correct database.yml file. after dad open a new terminal and list your environment variables and see if the MSF_DATABASE_CONFIG one shows and point to the correct location.

**Comment by darkoperator** [comment]
close do to no response.

**Comment by mlinton** [comment]
answer lies in not enough permissions by a non-privleged user:  run this instead:

rvmsudo bundle install
