### ISSUE TITLE
Bundle install won't work

### ISSUE THREAD

**Issue by martinquist** [darkoperator/MSF-Installer#41]
Here's what I'm getting on my Yosemite 10.10.2

maqu@MQ-MBP:~$ bundle install
Could not locate Gemfile
maqu@MQ-MBP:~$ gem install rake --version "10.1.0"
Fetching: rake-10.1.0.gem (100%)
Successfully installed rake-10.1.0
1 gem installed
Installing ri documentation for rake-10.1.0...
Installing RDoc documentation for rake-10.1.0...
maqu@MQ-MBP:~$ msfconsole
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.
maqu@MQ-MBP:~$ bundle install
Could not locate Gemfile
maqu@MQ-MBP:~$ gem install rake --version "10.4.2"
Fetching: rake-10.4.2.gem (100%)
Successfully installed rake-10.4.2
1 gem installed
Installing ri documentation for rake-10.4.2...
Installing RDoc documentation for rake-10.4.2...
maqu@MQ-MBP:~$ bundle install
Could not locate Gemfile
maqu@MQ-MBP:~$ msfconsole
Could not find i18n-0.7.0 in any of the sources
Run `bundle install` to install missing gems.
maqu@MQ-MBP:~$ bundle install
Could not locate Gemfile

You know what to do?

**Comment by darkoperator** [comment]
change to the metasploit framework folder and run bundle install from there
cd /usr/local/share/metasploit-framework/
bundle install

**Comment by martinquist** [comment]
Thank you!
