### ISSUE TITLE
failed to create msf role when installing msf using script on mac

### ISSUE THREAD

**Issue by Drewshg312** [darkoperator/MSF-Installer#43]
Using OSX 10.10.2.
When executing msf_install getting problems with postgresql.
```    ...
[*] Checking if PostgreSQL is installed, using Homebrew to install it if not.
[*] Installing PostgreSQL
[*] Installation of PostgreSQL was successful
[*] Initiating postgres
[*] Configuring the database engine to start at logon
/Users/myAwesomeUser/Library/LaunchAgents/homebrew.mxcl.postgresql.plist -> /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
[*] Creating the MSF Database user msf with the password provided
[*] Failed to create the msf role
[*] Creating msf database and setting the owner to msf user
[*] Failed to create the msf database.
...    ```

The logfile:

```     ...
#### POSTGRESQL INSTALLATION ####
---- Installing PostgreSQL ----
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/postgresql-9.4.1.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/postgresql-9.4.1.yosemite.bottle.tar.gz
==> Pouring postgresql-9.4.1.yosemite.bottle.tar.gz
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.4) of PostgreSQL, see:
  http://www.postgresql.org/docs/9.4/static/upgrading.html

To have launchd start postgresql at login:
    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
Then to load postgresql now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
Or, if you don't want/need launchctl, you can just run:
    postgres -D /usr/local/var/postgres
==> Summary
🍺  /usr/local/Cellar/postgresql/9.4.1: 2989 files, 40M
---- Installation of PostgreSQL successful----
---- Initiating the PostgreSQL Database ----
The files belonging to this database system will be owned by user "myAwesomeUser".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... initdb: could not change permissions of directory "/usr/local/var/postgres": Operation not permitted
---- Postgres Version 9.4.1 ----
---- Starting PostgreSQL Server ----
pg_ctl: could not open PID file "/usr/local/var/postgres/postmaster.pid": Permission denied
---- Postgres Version 9.4.1 ----
---- Creating Metasploit DB user ----
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- Creation of Metasploit user failed ----
---- Creating Metasploit Database and assigning the role ----
createdb: could not connect to database template1: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (fe80::1) and accepting
	TCP/IP connections on port 5432?
---- Database creation failed ----
Cloning into '/usr/local/share/metasploit-framework'...
Checking out files:  21% (1639/7486)   
Checking out files:  22% (1647/7486)   
Checking out files:  23% (1722/7486)   
Checking out files:  24% (1797/7486)   
Checking out files:  25% (1872/7486)   
Checking out files:  26% (1947/7486)   
Checking out files:  27% (2022/7486)   
Checking out files:  28% (2097/7486)   
Checking out files:  29% (2171/7486)   
Checking out files:  30% (2246/7486)   
Checking out files:  31% (2321/7486)   
Checking out files:  32% (2396/7486)   
Checking out files:  33% (2471/7486)   
Checking out files:  34% (2546/7486)   
Checking out files:  35% (2621/7486)   
Checking out files:  36% (2695/7486)   
Checking out files:  37% (2770/7486)   
Checking out files:  38% (2845/7486)   
Checking out files:  39% (2920/7486)   
Checking out files:  40% (2995/7486)   
Checking out files:  41% (3070/7486)   
Checking out files:  42% (3145/7486)   
Checking out files:  43% (3219/7486)   
Checking out files:  44% (3294/7486)   
Checking out files:  45% (3369/7486)   
Checking out files:  46% (3444/7486)   
Checking out files:  47% (3519/7486)   
Checking out files:  48% (3594/7486)   
Checking out files:  49% (3669/7486)   
Checking out files:  50% (3743/7486)   
Checking out files:  51% (3818/7486)   
Checking out files:  52% (3893/7486)   
Checking out files:  53% (3968/7486)   
Checking out files:  54% (4043/7486)   
Checking out files:  55% (4118/7486)   
Checking out files:  56% (4193/7486)   
Checking out files:  57% (4268/7486)   
Checking out files:  58% (4342/7486)   
Checking out files:  59% (4417/7486)   
Checking out files:  60% (4492/7486)   
Checking out files:  61% (4567/7486)   
Checking out files:  62% (4642/7486)   
Checking out files:  63% (4717/7486)   
Checking out files:  64% (4792/7486)   
Checking out files:  65% (4866/7486)   
Checking out files:  66% (4941/7486)   
Checking out files:  67% (5016/7486)   
Checking out files:  68% (5091/7486)   
Checking out files:  69% (5166/7486)   
Checking out files:  69% (5227/7486)   
Checking out files:  70% (5241/7486)   
Checking out files:  71% (5316/7486)   
Checking out files:  72% (5390/7486)   
Checking out files:  73% (5465/7486)   
Checking out files:  74% (5540/7486)   
Checking out files:  75% (5615/7486)   
Checking out files:  76% (5690/7486)   
Checking out files:  77% (5765/7486)   
Checking out files:  78% (5840/7486)   
Checking out files:  79% (5914/7486)   
Checking out files:  80% (5989/7486)   
Checking out files:  81% (6064/7486)   
Checking out files:  82% (6139/7486)   
Checking out files:  83% (6214/7486)   
Checking out files:  84% (6289/7486)   
Checking out files:  85% (6364/7486)   
Checking out files:  86% (6438/7486)   
Checking out files:  87% (6513/7486)   
Checking out files:  88% (6588/7486)   
Checking out files:  89% (6663/7486)   
Checking out files:  90% (6738/7486)   
Checking out files:  91% (6813/7486)   
Checking out files:  92% (6888/7486)   
Checking out files:  93% (6962/7486)   
Checking out files:  94% (7037/7486)   
Checking out files:  95% (7112/7486)   
Checking out files:  96% (7187/7486)   
Checking out files:  97% (7262/7486)   
Checking out files:  98% (7337/7486)   
Checking out files:  99% (7412/7486)   
Checking out files: 100% (7486/7486)   
Checking out files: 100% (7486/7486), done.
---- Downloading the latest version of Armitage ---
---- Decompressing the latest version of Armitage ----
x armitage/
x armitage/armitage
x armitage/armitage.jar
x armitage/teamserver
x armitage/readme.txt
x armitage/armitage-logo.png
x armitage/whatsnew.txt
x armitage/cortana.jar    ```

**Comment by darkoperator** [comment]
What was the error in the install log?

**Comment by Drewshg312** [comment]
I think it's somewhere here:

```     ---- Installation of PostgreSQL successful----
---- Initiating the PostgreSQL Database ----
The files belonging to this database system will be owned by user "myAwesomeUser".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... initdb: could not change permissions of directory "/usr/local/var/postgres": Operation not permitted
---- Postgres Version 9.4.1 ----
---- Starting PostgreSQL Server ----
pg_ctl: could not open PID file "/usr/local/var/postgres/postmaster.pid": Permission denied
---- Postgres Version 9.4.1 ----
---- Creating Metasploit DB user ----
psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- Creation of Metasploit user failed ----
---- Creating Metasploit Database and assigning the role ----
createdb: could not connect to database template1: could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (fe80::1) and accepting
    TCP/IP connections on port 5432?
---- Database creation failed ----     ```

**Comment by darkoperator** [comment]
Looks like initdb could not change the permissions on the folder for some reason. If you try 

            initdb /usr/local/var/postgres
What do you get?

**Comment by Drewshg312** [comment]
-bash: init: command not found

**Comment by Drewshg312** [comment]
```    The files belonging to this database system will be owned by user "Andryuwka".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... initdb: could not change permissions of directory "/usr/local/var/postgres": Operation not permitted    ```

**Comment by darkoperator** [comment]
Weird looks as if it can not initialize properly. You did not sudo msf_install right? Seems as if brew was installed as root

**Comment by Drewshg312** [comment]
I didn't do sudo msf_install...
And I'm not sure if brew was installed as root (probably not but how can I check this?)

**Comment by darkoperator** [comment]
Run brew doctor

**Comment by Drewshg312** [comment]
says:
Your system is ready to brew

**Comment by darkoperator** [comment]
Do a a 
brew info postgresql
And follow the steps it shows, could be they changed for this version. Not near my home so no access to any of my lab systems until later today

**Comment by Drewshg312** [comment]
well I've tried this:
sudo bash msf_install.sh
and got this
    ...
Error: Cowardly refusing to `sudo brew install`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
...

**Comment by darkoperator** [comment]
Noooo the script should never be ran as sudo on OSX. Just run without sudo

brew info postgresql 

And follow the steps it shows

**Comment by Drewshg312** [comment]
I know - that's how I've checked that my homebrew executable isn't owned by root...
```brew info postgresql```
it says:
```- Conflicts with: postgres-xc``` (which is not installed anyways)
```    If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510   ```
but I'm doing it as well:
```    brew remove postgresql    ```
and
```    rm -rf /usr/local/var/postgres    ```
I just run out of ideas.. I'm in dispare that's why I'm writing here(((

**Comment by darkoperator** [comment]
ok the lets try the following, remove the current install

brew uninstall postgresql

rm any postgresql agent in ~/Library/LaunchAgents

reinstall using:

brew install postgresql

if the install is successful then:
initdb /usr/local/var/postgres

if this fails please do ls -la /usr/local so as to see the perms on that folder

**Comment by Drewshg312** [comment]
Well even after this I get same fail msg. 
```    $ ls -la /usr/local/var    ```
```    drwx------   3 Andryuwka  admin   102B Feb  7 16:39 ./
drwxr--r--   2 root       admin    68B Feb  7 16:39 postgres/
drwxrwxr-x  24 root       admin   816B Feb  4 19:13 ../
    ```

**Comment by Drewshg312** [comment]
but even if I change permissions to get this:
```    drwxrwxr-x   3 MyAwesomeUser  admin   102B Feb  7 16:34 postgres/    ```
initdb still shows the same problem((((

**Comment by darkoperator** [comment]
uhm no clue how there is a postgres folder as root! if you run all as a regular user there is not way that folder would be there. was there a previous postgresql db installed?, I would say run 

sudo rm -rf /usr/loca/var/postgres

once removed try the ignited command again that failed. That folder should not be there unless something was ran with sudo, su or as root.

**Comment by darkoperator** [comment]
problem with that is the file structure under it, that is why I recommend to completely wipe it and then do the ignited command

**Comment by Drewshg312** [comment]
what if there was a database there before?
Maybe that's a reason... Because I've reinstalled it so many times(more then 30 I think)
What should I do in this case? How can I wipe all the shit to be sure it's clean?

**Comment by darkoperator** [comment]
wow 30 times for a dev system is a lot of effort. I would say go through the commands in the script and delete and undo the mods it does. I think at one moment you either installed brew as root or ran the script as root and that was the problem. if there was a database file it means one of those scenarios. 

remove hombrew.
delete ~/.msf4 folder
remove metasploit-framework folder in /usr/local/share
undo modification to the bash profile and rc files

**Comment by Drewshg312** [comment]
ok, thanx... I'v done all except of reinstall homebrew... I have to quickly write the script for installing all the programs from homebrew and hb cask before trying this)))) lol

**Comment by darkoperator** [comment]
Go manual and not with a script. Best way to work on a none clean install

**Comment by Drewshg312** [comment]
So now I've got another problem. When script does the command
`psql postgres -c`
I got in log file this:
`---- Creating Metasploit DB user ----
psql: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory
---- Creation of Metasploit user failed ----
---- Creating Metasploit Database and assigning the role ----
createdb: could not connect to database template1: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory
---- Database creation failed ----`

**Comment by darkoperator** [comment]
To be honest my recommendation would be to run Metasploit in Linux. At the moment I can not replicate issues you are having.

**Comment by darkoperator** [comment]
Scripts assumes a clean system and your problem are more related with running brew as root and installing Postgres as so. You will have to go in to the console app, look at the problems with it starting, fix those by hand and finish the install by hand. Sadly I'm taking care of my wife and 2 kids after she had an accident and don't have much time to offer to help fix Postgres and help you finish installing a dev of env on OSX

**Comment by Drewshg312** [comment]
Thank you for your answer! I wish your family to recover as soon as possible! Take care bud!!

**Comment by Drewshg312** [comment]
Well I've modified a code and fixed the problem... I also changed the rvm option with rbenv (from homebrew - which is great) - kinda neat alternative, light and organic (installs also all useful plugins for rbenv from homebrew)... Now it works (at least on osx lol) - doesn't matter if it's a first time or not... installed after a complete wipe of all the components (tested many times)))). As I understood right you don't need to initdb if it's not a first time postgresql installed on the machine (please correct me if I'm wrong)... Now have to find out how to use github and fork it (if I'm allowed to do so?). Needs to be tested on linux (spend only a few days to understand and modify the code so not sure how it will work on actual linux machine)

**Comment by darkoperator** [comment]
Correct the initdb is only needed once. Have you read the Rapid7 dev environment setup guide? The script is to automate as much as possible of that process. OS X lags in performance and on some modules causes problems do to the way it does sockets. That is why I always refer to it as a "dev" setup. You will see in their docs that you can fork it in to your own Github repo.

**Comment by thomas-dc** [comment]
I am having the same issue...

**Comment by darkoperator** [comment]
Same OS (OSX) same errors in the log?

**Comment by thomas-dc** [comment]
Yeah exactly the same. I am at a stop right now. Spent to much time on it. Will trouble shoot more in the morning.

V/R
Thomas Edward Turner
(H) 703-670-9352
(C) 850-866-1352
Skype: Thomas.t8

**Comment by thomas-dc** [comment]
I am also having issues with pg gem will not bundle

V/R
Thomas Edward Turner
(H) 703-670-9352
(C) 850-866-1352
Skype: Thomas.t8

**Comment by darkoperator** [comment]
to check:
You ran the script only once?
The system never had macports or brew installed?
you did not ran it as root?
Did you tried running the install commands by hand?

**Comment by thomas-dc** [comment]
I had macports, but uninstalled it prior. I have always had brew. I do not believe I ran anything as root unless it was requesting. I actually did do a manual install first. Then after having issues with that gem I got lazy and just tried using the script.

V/R
Thomas Edward Turner
(H) 703-670-9352
(C) 850-866-1352
Skype: Thomas.t8

**Comment by thomas-dc** [comment]
Suppose I need to recompile the gems being I had macports. Never had an issue before. I have been using both macports and brew. But I never really did anything with ruby. Kinda lost at this point. What do you think..?

V/R
Thomas Edward Turner
(H) 703-670-9352
(C) 850-866-1352
Skype: Thomas.t8

**Comment by thomas-dc** [comment]
I ran the script multiple times. Before each additional execution of script - I would uninstall Postgres. Then run the script. Everything works well until it creates the msf database user. 

V/R
Thomas Edward Turner
(H) 703-670-9352
(C) 850-866-1352
Skype: Thomas.t8

**Comment by darkoperator** [comment]
What do you get when you try by hand?

sudo -s su postgres
createuser msf -P -S -R -D 
createdb -O msf msf 
exit 
exit

**Comment by Drewshg312** [comment]
After uninstalling postgresql restart your mac, open new shell and run the script. You will get this error until you do so. (Even if you feel sceptic about restarting - try it). If Gems install fails after first restart, just clean everything, restart and try again. I've also noticed that in my case ruby 1.9.3 is not enough (seems like it's not supported anymore) so I added installing 2.1.5 before 1.9.3 and after that it works stable (I noticed that default ruby for installing msf still should be 1.9.3. Added 2.1.5 only for successful gems installation)... I'm also using rbenv instead of rvm (but it's just a preference - obviously I'm not an experienced ruby coder lol)

**Comment by darkoperator** [comment]
one problem with Ruby 2.x is that symlink will not work, you will have to run from onside the metasploit-framework folder. there is an issue open by HD on it but see a lot of debate and back and forth by the dev team for 2 weeks no with no progress

**Comment by Drewshg312** [comment]
no it works with 2.1.5 set as default and from nay location. After `gem install bundler` and `bundle install` Checked it right now. Works great! Maybe they fixed it already... dunno

**Comment by thomas-dc** [comment]
Thomass-MacBook-Pro:MSF-Installer-master theoneandonlythomast$ sudo -s su postgres
Password:
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
bash-3.2$

**Comment by darkoperator** [comment]
gave you the steps for linux instead of OS X 

http://www.darkoperator.com/installing-metasploit-framewor/ <http://www.darkoperator.com/installing-metasploit-framewor/>

follow the steps there for the postgres config

**Comment by Drewshg312** [comment]
if you want to be able to install it any time on any mac automatically, the script should work fine if you do this before running script:
```    
brew uninstall postgresql
sudo rm -rf /usr/local/var/postgres ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
sudo rm -rf /usr/local/share/armitage /usr/local/share/metasploit-framework ~/.msf4
sudo shutdown -r now    ```

Or do it manually as darkoperator tells...

**Comment by Drewshg312** [comment]
and you don't need to do
`initdb /usr/local/var/postgres`
if you already installed postgresql on this mac... so modify the script accordingly..
