### ISSUE TITLE
Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1

### ISSUE THREAD

**Issue by d1rtd0g** [darkoperator/MSF-Installer#45]
On Debian, msfconsole cannot launch, 
"Could not find metasploit_data_models-0.23.0 in any of the sources
Run `bundle install` to install missing gems."
cd /usr/local/share/metasploit-framework
bundle install
Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1.
An error occurred while installing metasploit_data_models (0.23.0), and Bundler
cannot continue.
Make sure that `gem install metasploit_data_models -v '0.23.0'` succeeds before
bundling.

**Comment by darkoperator** [comment]
There is an issue with symlinks https://github.com/rapid7/metasploit-framework/issues/4602#issuecomment-74906292 . Go in to the metasploit-framework run bundler from there and run msfconsole from inside of it ./msfconsole

**Comment by theinvinciblesun** [comment]
metasploit_data_models was updated 7 days ago and now supports only ruby >=2.1

**Comment by darkoperator** [comment]
Then it is time for me to pull the script offline, re-work it when I do have time. My plan is that it will be RVM only. No symlinks and be exactly as the R7 guide for dev env.

**Comment by d1rtd0g** [comment]
When I tried to update ruby, apparently it's not supported from the gem install command in linux, it said it would probably break my system. I didn't choose to install rvm the first time I ran your script because I was hoping the install would be simple. so to update i tried using ruby-build and rbenv instead, since it seem to be pretty recommended over RVM. I had to pull the new updates from git because the apt-get package was not up to date, and not showing the new versions up to 2.1. I tried changing the version of ruby for that local project, then running "bundle install". It still didn't work I was probably missing another step maybe need to start the project new and install again from the new version. Anyway I was able to get it working using your advice, ran bundler and launched ./msfconsole from the /metaspoit-framework directory. Seem to work perfectly other than symlink broken. Thanks

**Comment by palinceline** [comment]
I cant even run bundler because it says:
Eness-MacBook-Pro:msf EnesWitwit$ bundler
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.6.11
Using multi_json 1.0.4
Using activesupport 3.2.21
Using builder 3.0.4
Using activemodel 3.2.21
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.2
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.21
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.21
Using arel 3.0.3
Using tzinfo 0.3.42
Using activerecord 3.2.21
Using activeresource 3.2.21
Using arel-helpers 2.1.0
Using ffi 1.9.3
Using childprocess 0.5.3
Using diff-lcs 1.2.5
Using json 1.8.1
Using gherkin 2.11.6
Using cucumber 1.2.1
Using rspec-expectations 2.99.2
Using aruba 0.6.1
Using bcrypt 3.1.10
Using bundler 1.8.2
Using mini_portile 0.6.1
Using nokogiri 1.6.5
Using xpath 2.0.0
Using capybara 2.4.1
Using coderay 1.1.0
Using rack-ssl 1.3.4
Using rdoc 3.12.2
Using thor 0.19.1
Using railties 3.2.21
Using rails 3.2.21
Using cucumber-rails 1.4.0
Using factory_girl 4.4.0
Using factory_girl_rails 4.4.1
Using fivemat 1.2.1
Using rkelly-remix 0.0.6
Using jsobfu 0.2.1
Using metasploit-concern 0.3.0
Using metasploit-model 0.29.0
Using pg 0.18.1
Using recog 1.0.16

Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1.
An error occurred while installing metasploit_data_models (0.23.0), and Bundler
cannot continue.
What do I do now? im confused!

**Comment by palinceline** [comment]
Eness-MacBook-Pro:msf EnesWitwit$ bundle binstubs metasploit-framework --path=$(dirname $(which msfconsole)) --force
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/msf/.bundle
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/settings.rb:153:in `set_key'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/settings.rb:21:in `[]='
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/cli/binstubs.rb:13:in `run'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/cli.rb:209:in `binstubs'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/cli.rb:10:in `start'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/bin/bundle:20:in `block in <top (required)>'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.8.2/bin/bundle:18:in `<top (required)>'
    /usr/local/bin/bundle:23:in `load'
    /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.8.2
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    GEM_HOME  /usr/local/lib/ruby/gems/2.1.0
    GEM_PATH  /usr/local/lib/ruby/gems/2.1.0:/Users/EnesWitwit/.gem/ruby/2.1.0:/usr/local/Cellar/ruby21/2.1.5/lib/ruby/gems/2.1.0
    Git       1.9.3 (Apple Git-50)

Bundler settings

    bin
      Set for your local app (/opt/msf/.bundle/config): "/usr/local/bin"
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fopt%2Fmsf%2F.bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by darkoperator** [comment]
Metasploit now only supports ruby 2.1 or higher so you will have to uninstall 1.9.3 and install 2.1

**Comment by daltonfury42** [comment]
I have ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux] installed. Still I am getting the error.
![screenshot from 2015-03-01 13 05 19](https://cloud.githubusercontent.com/assets/11256376/6430831/c563a472-c041-11e4-9b80-52178fc9ef11.png)

**Comment by darkoperator** [comment]
weird, Same version as I with no problems. Script is no longer supported I suspended work it for now. if you try to use it again it will simply exit do to all the changes R7 makes making it harder and harder to install without their commercial installer. Are you using RVM, rbenv or manual ruby compile? on Linux you need to uninstall any Ruby on the system not managed by RVM before trying just in case.

**Comment by darkoperator** [comment]
by the way nice name, same name as the pseudonym of one of my favorite authors ;)

**Comment by JetQin** [comment]
i have the same error,i install ruby 2.1.5 version,but when i execute <code>bundle install</code>
it tells me
```
Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1.
An error occurred while installing metasploit_data_models (0.23.1), and Bundler cannot continue.
Make sure that `gem install metasploit_data_models -v '0.23.1'` succeeds before bundling.
```

did anyone knows what the problem is?
```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

```

**Comment by darkoperator** [comment]
Check in the Metasploit IRC channel if they know the reason of the issue

**Comment by darkoperator** [comment]
@JetQin do check that you do not have Ruby installed using APT since it may install in the path a none 2.1 ruby version and it is picking that one up and only use either RVM or rbenv

**Comment by hmoore-r7** [comment]
Make sure you are using the Gemfile.lock that we ship (git checkout -- Gemfile.lock), its easy to get out of sync if you run 'bundle update' or similar.

**Comment by onskulis** [comment]
@d1rtd0g, im having same issue, did you find a solution?

**Comment by d1rtd0g** [comment]
yeah, I followed what @darkoperator suggested: 
>Go in to the metasploit-framework directory
>run bundler
>launch msfconsole from metasploit-framework directory with ./msfconsole

**Comment by onskulis** [comment]
Its very strange, im getting::

'Errno::EPERM: Operation not permitted @ chmod_internal - /opt/metasploit-framework/./msfbinscan
An error occurred while installing metasploit-framework (4.11.0.pre.dev), and Bundler cannot continue.
Make sure that `gem install metasploit-framework -v '4.11.0.pre.dev'` succeeds before bundling.'

When I try to run bundler or install bundle as normal user.

And Im getting::

'Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1.
An error occurred while installing metasploit_data_models (0.23.1), and Bundler cannot continue.
Make sure that `gem install metasploit_data_models -v '0.23.1'` succeeds before bundling'

If I try to run bundle or install bundle as root user or sudo.

I also get a warning:

'Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all
non-root users on this machine.'

All Files inside /opt/metasploit-framework has 755 permissions and belongs to root.

Could someone help me please?

Ruby version: ruby 2.1.5p273 (2014-11-13 revision 48405) [i686-linux]

**Comment by ozzy76** [comment]
onskulis, did you find a solution that worked? I'm getting the same errors and I've tried all the above solutions. This one is a challenge

An error occurred while installing metasploit-framework (4.11.0.pre.dev), and Bundler cannot continue.
Make sure that `gem install metasploit-framework -v '4.11.0.pre.dev'` succeeds before bundling.
*****@eri-ub14:/usr/local/share/metasploit-framework$ gem install metasploit-framework -v '4.11.0.pre.dev'
ERROR:  Could not find a valid gem 'metasploit-framework' (= 4.11.0.pre.dev) in any repository

Thanks in advance

**Comment by darkoperator** [comment]
Are you running it in /usr/local/share/metasploit-framework ?

**Comment by ozzy76** [comment]
Hey darkoperator, I'm running everything in that directory which is strange. Deleted and cloned again to make sure the Gemfile was cool and it's still unhappy. I'll keep grindin', thanks for responding.

**Comment by net-ninja** [comment]
the answer is this:

After installing ruby 2.1, you need to re-install bundler. so the solution is

sudo gem install bundler

**Comment by cmurmann** [comment]
It didnt fix it... I still have the same thing, even after chmod and reinstalling bundler with sudo.

Errno::EPERM: Operation not permitted @ chmod_internal - /opt/metasploit-framework/./msfbinscan
An error occurred while installing metasploit-framework (4.11.0.pre.dev), and Bundler cannot continue.
Make sure that `gem install metasploit-framework -v '4.11.0.pre.dev'` succeeds before bundling.

**Comment by hmoore-r7** [comment]
@cmurmann Looks like you need to run this as root

**Comment by cmurmann** [comment]
Just didn't do it cause of the Root/Permission alert concerning the users, but I'll just setup the permissions later.

Just did it and it work fine. - Thanks
